name: Submodule Updates

on:
  workflow_dispatch:

###############
# Set the Job #
###############
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      PARENT_REPOSITORY1: 'Foundry-VTT-PF2-German/lang-de-pf2e'
      PARENT_REPOSITORY2: 'Foundry-VTT-PF2-German/module-builder'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'Foundry-VTT-PF2-German'

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      ####################################
      # Run the action against code base #
      ####################################
      - name: Update lang-de-pf2e
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.SUBMODULE_UPDATE }}
          parent_repository: ${{ env.PARENT_REPOSITORY1 }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
      
      - name: Update adventure-extractor
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.SUBMODULE_UPDATE }}
          parent_repository: ${{ env.PARENT_REPOSITORY2 }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
