name: Submodule Updates

##############################################
# Start Job on merged pull request into main #
##############################################
on:
  pull_request:
    types: [closed]
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    if: "github.event.pull_request.merged == true"
    name: Submodule update
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'Foundry-VTT-PF2-German/lang-de-pf2e'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'Foundry-VTT-PF2-German'

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.SUBMODULE_UPDATE }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
